# Generated by Django 4.0.5 on 2022-07-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='inputTestCases',
            field=models.TextField(default='', help_text='Input Test Cases'),
        ),
        migrations.AddField(
            model_name='problem',
            name='outputTestCases',
            field=models.TextField(default='', help_text='Output Test Cases'),
        ),
    ]
