# Generated by Django 4.0.5 on 2022-06-29 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('compiler', models.CharField(choices=[], max_length=30)),
                ('verdict', models.CharField(choices=[('AC', 'accepted'), ('WA', 'wrong answer'), ('TLE', 'time limit exceeded'), ('CE', 'compile error'), ('RE', 'runtime error'), ('TEST', 'testing')], default='TEST', max_length=4)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
